version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: dockerfiles/db.Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost -p 5432",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: dockerfiles/sv.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      DB_ADDRESS: "db"
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      SHORTENER_URL: ${SHORTENER_URL}
